config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
get '/home' , to: 'pages#home'

  get '/martists' , to: 'martists#index'
   get '/martists/new', to: 'martists#new', as: 'makeup_profile'
   post '/martists', to: 'martists#create'
    get  '/martists/:id/edit', to: 'martists#edit', as: 'edit_martist'
    patch '/martists/:id', to: 'martists#update'
     get 'martists/:id', to: 'martists#show', as: 'martist'

  
 get '/bookings' , to: 'booking#new' ,as: 'new_booking'
 get '/bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
 patch  '/bookings/:id', to: 'bookings#update'
 get 'bookings/:id', to: 'bookings#show' , as: 'booking'
 delete '/bookings/:id', to: 'bookings#destroy'
 
 get '/photos', to: 'photos#index'
 get '/photos/new', to: 'photos#new', as: 'new_photo'
 post '/photos', to: 'photos#create'
 get '/photos/:id/edit', to: 'photos#edit', as: 'edit_photo'
 patch '/photos/:id', to: 'photos#update'
 get 'photos/:id', to: 'photos#show', as: 'photo'
 delete '/photos/:id', to: 'photos#destroy'
  
 


  

end

app/models/booking.rb
class Booking <ActiveRecord::Base
  belongs_to :martist
  belongs_to :client
end

app/models/categor.rb
class Categor <ActiveRecord::Base
  
end

app/models/client.rb
class Client <ActiveRecord::Base
  has_many :bookings
end

app/models/login.rb
class Login <ActiveRecord::Base
  
end

app/models/martist.rb
class Martist <ActiveRecord::Base
  has_many :bookings
  has_many :photos
 # validates :lastname, presence: true, length: {minimum: 2, maximum:20}
  #validates :firstname, presence: true, length: {minimum: 2, maximum:20}
  #validates :profilemessage, presence: true
#  mount_uploader :picture, PictureUploader
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :martist
  mount_uploader :picture, PictureUploader   
  validate :picture_size
  
  private 
    def picture_size
      if picture.size > 20.megabytes
        errors.add(:picture, "should be less than 20MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/martists_controller.rb
class MartistsController <ApplicationController
  
  def index
    
    @martists = Martist.all
    
  end
     def show
       #binding.pry  
       #type in params to see th eactual id that was passed 
       @martist = Martist.find(params[:id])
     end
     
     
     def  new
       
      @martist = Martist.new
       
     end
     
     def create
      # binding.pry
      #type in params to see th eactual id that was passed ,rails 4 force you to list what fields that the application can accept,so a private method is created below
      @martist = Martist.new(martist_params)
     # @martist.booking = Martist.find(1)
     
      if  @martist.save
        flash[:success]  = "Your profile was created succesfully"     #sending a notification that recipee was created 
        redirect_to martists_path   #reirecting to index page,so martist profile would be displayed 
      else
        render :new
      end
     end
     
     
    def edit  #remeber to cretae a template like similar for for creating profilr for edit
       @martist = Martist.find(params[:id])  #params contain the id
        
    end
    
    def update
      @martist = Martist.find(params[:id])
      if @martist.update(martist_params)
         #do something
       flash[:success] = "Your profile was updates succesfully"
       redirect_to martist_path(@martist)
         else
          render :edit
      end
    end
    
     
      private
        
        
        def martist_params
          
          params.require(:martist).permit(:lastname, :firstname, :email, :username, :profilemessage,:country_located, :culture )
        end
          
          
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
  def home
  end 
end

app/controllers/photos_controller.rb
class PhotosController <ApplicationController
 
 def index
  @photos = Photo.all
 end
 
 
 def show 
  @photo = Photo.find(params[:id])
 end
 
 
 def new 
  @photo = Photo.new
 end
 
 def create 
  #binding.pry
   @photo = Photo.new(photo_params)
   @photo.martist = Martist.find(21)
   
   
   if @photo.save
    # do something
    flash[:sucess] ="Your photo was uploaded succesfully"
    redirect_to photos_path
   else 
    render :new
   end
 end
 
 def edit
  @photo = Photo.find(params[:id])
 end
 
 
 def update
   @photo = Photo.find(params[:id])
   if @photo.update(photo_params)
     flash[:sucess] ="Your photo was editted succesfully"
     redirect_to photos_path(@photo)
   else 
    render :edit
   end 
 end
 
 private  #defining explicitly what paramters the form would accept  in this private method
 
     def photo_params
       params.require(:photo).permit(:summary, :picture)
     end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p>&copy; BeautyTray </p>
  </div>

app/views/layouts/_navigation.erb
 <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%=link_to "Beauty Tray", "", id:"logo" %></a>
    </div>

   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default"> <span class="glyphicon glyphicon-search"></span></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter Artist By <span class="caret"></span></a>
                <ul class="dropdown-menu">
                   <li><%=link_to "Location", "" %></li>
                   <li><%=link_to "Tradition", "" %></li>
                   <li><%=link_to "Ceremony", "" %></li>
                </ul>
           </li>
        <li><%=link_to "Home", "" %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                     <li><%=link_to "Log Out", "" %></li>
                     <li><%=link_to "Password and Security", "" %></li>
                  </ul>
                </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%=link_to "Beauty Tray", photos_path , id:"logo" %></a>
    </div>

   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default"> <span class="glyphicon glyphicon-search"></span></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter Artist By <span class="caret"></span></a>
                <ul class="dropdown-menu">
                   <li><%=link_to "Location", "" %></li>
                   <li><%=link_to "Tradition", "" %></li>
                   <li><%=link_to "Ceremony", "" %></li>
                </ul>
           </li>
        <li><%=link_to "Home", photos_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                     <li><%=link_to "Log in", "" %></li>
                     <li><%=link_to "Sign up", "" %></li>
                  </ul>
                </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beauty Tray</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     <%= render 'layouts/navigation' %>
<div class="container">
<%= yield %>
   <%= render 'layouts/footer' %> 
</div>

</body>+
</html>

app/views/martists/_form.html.erb
<!---form to create or add profile for makeupartist----->


<% if @martist.errors.any? %>
<div class="row">
  <div class="alert alert-danger col-md-8 col-md-offset-2">
    <h5>Please complete your profile:</h5>
      <ul>
        <% @martist.errors.full.messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>  
      </ul>
    
  </div>
</div>
<% end %>
<div class="col-md-2 profile_pix">
  <section class="profile_picture">
    for uploading profile pic
  </section>
</div>

<div class="row">
    <div class= "well col-md-8 col-md-offset-2">
        <%= form_for(@martist, html: { multipart: true}) do |f| %> <!--for picture upload--->
        <%= f.label :lastname %>
        <%=f.text_field :lastname%>
        
        <%= f.label :firstname %>
        <%=f.text_field :firstname %>
        
        
        <%= f.label :username %>
        <%=f.text_field :username %>
        
        <%= f.label :email %>
        <%=f.text_field :email %>
        
        <%= f.label :profile_message %>
        <%=f.text_area :profilemessage, rows:8 %>
        
        <%= f.label :country_located %>
        <%=f.text_field :lastname %>
        
        
        <%= f.label :culture%>
        <%=f.text_field :culture %>
        
        <span class="martistpicture">
          <%= f.file_field :picture, accept: 'image/jpeg, image/gift,image/png'%> <!---field to accept any picture format , remeber to include this field im martist params in martist controller-->
        </span>
        
        <%= f.submit(@martist.new_record? ? 'Create Profile' : 'Edit Profile', class: "btn btn-default" ) %> <!---we only want create recipee to show when a new form is added --->
      <% end %>
    </div>
</div>

<script type="text/javascript">
  $('#martist_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 10) {
      alert('maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

<!---heroku come preinstalled with image magick ,but in our development environment , we need to type in the   code 
  sudo apt-get update
  sudo apt-get install imagemagick --fix-missing    
  ---->

app/views/martists/edit.html.erb
<!---<p>
  </h1>Edit Your Profile</h1>
  <hr/>
</p>---><%= render 'shared/page_title' , title: "Edit your Profile" %>

<%= render 'form' %>

<!--if you want the shared partial refernced to a object,you would enbed and render to   'folder/filename, title: @object.atributename , (object is thename of the model or entity)---->

app/views/martists/index.html.erb
<!-------index page  for makeup artist-->

<% @martists.each do |martist| %> <!--iterating through each makeup artist in the makeup artist table,  martist  is the object, view gets an object passed through it from a controller --->
  <div class="row">
   
    
    <div class="col-lg-8 well"> 
       <h1>profile pix</h1>
      <h4><%= link_to martist.username ,martist_path(martist) %></h4>
     <p><%= martist.profilemessage %></p>
     <p>
         <span class= 'quiet'><small><%= time_ago_in_words(martist.created_at) %> ago</small></span>
     </p>
    </div>   
     
  </div>
   
<% end %>

app/views/martists/new.html.erb
<!----formto create makeup artist profile-------->

<%= render 'shared/page_title' , title: "Create your Profile"%>
<%= render 'form' %>


<!----creating a barnch to secure master folder coomand: git checkout -b image-uploader (where image uploader is the name of the branch)
-get '/martist/:martist_id/photos' , to: 'martists#index3'
  
 resources :martists do 
resources :photos
end----> 

app/views/martists/show.html.erb
	
	<!---show page for makeup artist------>
	
	
	<div class="container">
    	<div class="row">	
    		<div class="col-md-3 col-xs-1">
    			</div>
    		<div class="col-md-4 col-xs-12"><h1><%= @martist.username %></h1> </div>
    		
    		<div class="col-md-3 col-xs-3"><%= link_to "Edit Profile", edit_martist_path(@martist), class:"glyphicon glyphicon-option-horizontal btn btn-default"%></div>
    			<div class="col-md-3 col-xs-3"><%= link_to "Upload new photo", new_photo_path, class:"glyphicon glyphicon-option-horizontal btn btn-default"%></div>
    		<div class="col-md-6 col-xs-12"><h3><%= @martist.profilemessage %></h3> </div>
    		
    		<div class="col-md-3 col-xs-12"><h1><%= link_to "Book an appointment" , ""%></h1></div>
    	</div> 
	 
	 <div class="row">
	 	<div class="col-md-9 col-xs-6">
			 <!--this div is displayed  if htere is a picture-->
		</div><!-- end feature -->
	 </div>
	 
	 </div>
	 
	 
	 

app/views/pages/home.html.erb
<h1>Carosel and sign up setting </h1>

app/views/photos/_form.html.erb
<!------form partial for picture upload---------->
<div class=row>
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@photo, html: {multipart: true}) do |f|%>
      <%=f.label :Add_a_tittle %>
      <%= f.text_area :summary, rows:12%>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
      </span>
      <%=f.submit(@photo.new_record? ?  'Upload a  new photo' : 'Edit Photo', class:"btn btn-default") %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
   $('#photo_picture').bind('change', function() {
     size_in_megabytes = this.files[0].size/1024/1024;
     if(size_in_megabytes > 20){
       alert('Maximum size file is 20MB please choose smaller file ');
     }
   });
</script>

app/views/photos/edit.html.erb
<!---form page to edit  or upload new photo---->
<%= render 'form'%>

app/views/photos/index.html.erb
<!-- index page for all uploades picrtures---->
<% @photos.each do |photo| %> <!--iterating through each photo in the photos table,  photos is the object, view gets an object passed through it from a controller --->
  <div class="row">

    
    <div class="col-lg-8 well"> 
      <%= link_to photo_path(photo) do %>
     <%= image_tag(photo.picture.url, size: "200x250", class: "img-responsive center-block") if photo.picture? %>
      <% end %>
     <h5><%=link_to photo.martist.username , photo_path(photo)%></h5>
     <p><%= photo.summary %></p>
     
     <p>
         <span class= 'quiet'><small><%= time_ago_in_words(photo.created_at) %> ago</small></span>
     </p>
    </div>   
     
  </div>
  <hr/>
    
<% end %> 

  

app/views/photos/new.html.erb
<!---form page to create or uploa new photo---->
<%= render 'form' %>

app/views/photos/show.html.erb
<!------show larger picture  view for makeupartist photo that was newly uploaded -->
<div class="row">
  
  <div class="col-md-4 pull-right center " >
    <h5><%= @photo.summary  %></h5>
   
  </div>
  <div class="col-md-8 pull-right center " >
      <div class="well photo-space">
           <%= image_tag(@photo.picture.url, size: "400x450", class: "img-responsive center-block") if @photo.picture? %>
          <p class="text-right"><small><%= link_to "Edit Photo" ,edit_photo_path(@photo) %></Edit></small></p>
      </div>
   </div>
  </div>
  
  <h5>view all images of <%=link_to  @photo.martist.username , "" %>'s album</h5>
  

  
  
</div>

app/views/shared/_page_title.html.erb
<p>
  </h1><%= title %></h1>
  <hr/>
</p>